module.exports = {
    messages: {
        required: "[{name}]: 不能为空值",
        contains: "[{name}]: 必须包含 {args}",
        mobile: "[{name}]: 手机号码格式错误",
        equals: "[{name}]: 的值应该和 {args} 相等",
        different: "[{name}]: 的值应该和 {args} 不相等",
        before: "[{name}]: 应该在 {args} 之前",
        after: "[{name}]: 应该在 {args} 之后",
        alpha: "[{name}]: 的值只能是 [a-zA-Z] 组成",
        alphaDashr: "[{name}]: 的值只能是 [a-zA-Z] 组成",
        alphaNumeric: "[{name}]: 的值只能是 [a-zA-Z0-9] 组成",
        alphaNumericDash: "[{name}]: 的值只能是 [a-zA-Z0-9] 组成",
        ascli: "[{name}]: 的值只能由 ASCII 组成",
        base64: "[{name}]: 的值必须是 base64 编码",
        byteLength: "[{name}]: 的字节长度错误",
        creditcard: "[{name}]: 需要是信用卡数字",
        currency: "[{name}]: 应该是货币格式",
        date: "[{name}]: 应该是日期格式",
        decimal: "[{name}]: 应该是小数格式",
        divisibleBy: "[{name}]: 需要被 {args} 整除",
        email: "[{name}]: 需要是个 email 格式",
        fqdn: "[{name}]: 需要是个合格的域名",
        float: "[{name}]: 浮点数格式错误 {args}",
        fullWidth: "[{name}]: 应该包含宽字节字符",
        halfWidth: "[{name}]: 应该包含半字节字符",
        hexColor: "[{name}]: 需要是个十六进制颜色值",
        hex: "[{name}]: 需要是十六进制",
        ip: "[{name}]: 需要是 ip 格式",
        ip4: "[{name}]: 需要是 ip4 格式",
        ip6: "[{name}]: 需要是 ip6 格式",
        isbn: "[{name}]: 需要是图书编码",
        isin: "[{name}]: 需要是证券识别编码",
        iso8601: "[{name}]: 需要是 iso8601 日期格式",
        in: "[{name}]: 应该在这些值中：{args}",
        noin: "[{name}]: 不应该在这些值中：{args}",
        int: "[{name}]: 整数格式错误：{args}",
        min: "[{name}]: 不能小于 {args}",
        max: "[{name}]: 不能大于 {args}",
        length: "[{name}]: 字符长度错误：{args}",
        minLength: "[{name}]: 长度不能小于 {args}",
        maxLength: "[{name}]: 长度不能大于 {args}",
        lowercase: "[{name}]: 需要都是小写字母",
        uppercase: "[{name}]: 需要都是大写字母",
        mongoId: "[{name}]: 应该是 MongoDB 的 ObjectID",
        multibyte: "[{name}]: 应该包含多字节字符",
        url: "[{name}]: 应该是个 url",
        order: "[{name}]: 数据库查询 order 格式错误",
        field: "[{name}]: 数据库查询 field 格式错误",
        image: "[{name}]: 上传的文件应该是个图片",
        startWith: "[{name}]: 应该以 {args} 打头",
        endWith: "[{name}]: 应该以 {args} 结尾",
        string: "[{name}]: 值为字符串",
        array: "[{name}]: 值为数组",
        boolean: "[{name}]: 值为布尔类型",
        object: "[{name}]: 值为对象",
    }
};